server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  location / {
      try_files $uri /index.html;
  }

  gzip on;
  gzip_types text/plain text/css application/javascript application/json image/svg+xml;
  gzip_min_length 1024;
  gzip_vary on;

  location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?|ttf|eot)$ {
      expires 1y;
      add_header Cache-Control "public";
  }

  add_header X-Content-Type-Options nosniff;
  add_header X-Frame-Options SAMEORIGIN;
  add_header X-XSS-Protection "1; mode=block";

  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;
}

