CREATE TABLE user_codes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(100) NOT NULL,
    code VARCHAR(100) NOT NULL,
    is_system BOOLEAN DEFAULT FALSE,

    UNIQUE(category, code)
);


CREATE TABLE translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR(70) NOT NULL,
    record_id BIGINT NOT NULL,
    field_name VARCHAR(70) NOT NULL,
    language_code VARCHAR(10) NOT NULL,
    value VARCHAR(255) NOT NULL,

    UNIQUE(table_name, record_id, field_name, language_code)
);

CREATE INDEX idx_translations_lookup
    ON translations(table_name, record_id, field_name, language_code);


CREATE TABLE date_descriptors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_type VARCHAR(50) NOT NULL,

    free_text VARCHAR(255),

    start_qualifier VARCHAR(50),
    start_year INT,
    start_month INT,
    start_day INT,

    end_qualifier VARCHAR(50),
    end_year INT,
    end_month INT,
    end_day INT,

    sort_date_time_min TIMESTAMP,
    sort_date_time_max TIMESTAMP
);

CREATE INDEX idx_dd_sort_min  ON date_descriptors (sort_date_time_min);
CREATE INDEX idx_dd_sort_max  ON date_descriptors (sort_date_time_max);
CREATE INDEX idx_dd_date_type ON date_descriptors (date_type);



CREATE TABLE locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);



CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id BIGINT NOT NULL,
    cached_start_sort_date_time TIMESTAMP,
    cached_end_sort_date_time TIMESTAMP,
    start_date_id BIGINT,
    end_date_id BIGINT,
    main_location_id BIGINT,

    CONSTRAINT fk_events_type FOREIGN KEY (type_id) REFERENCES user_codes(id),
    CONSTRAINT fk_events_start_date FOREIGN KEY (start_date_id) REFERENCES date_descriptors(id),
    CONSTRAINT fk_events_end_date FOREIGN KEY (end_date_id) REFERENCES date_descriptors(id),
    CONSTRAINT fk_events_main_location FOREIGN KEY (main_location_id) REFERENCES locations(id) ON DELETE SET NULL
);



CREATE TABLE people (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cached_given_name VARCHAR(255),
    cached_surname VARCHAR(255),
    sex VARCHAR(20),
    life_state VARCHAR(20),
    birth_event_id BIGINT,
    death_event_id BIGINT,

    CONSTRAINT fk_people_birth_event FOREIGN KEY (birth_event_id)
        REFERENCES events(id) ON DELETE SET NULL,
    CONSTRAINT fk_people_death_event FOREIGN KEY (death_event_id)
        REFERENCES events(id) ON DELETE SET NULL
);


CREATE TABLE person_gedcom_data (
    person_id BIGINT PRIMARY KEY,
    ged_uid VARCHAR(100),
    ged_ref_id VARCHAR(100) NOT NULL,
    raw_given_name VARCHAR(255),
    raw_surname VARCHAR(255),
    raw_sex VARCHAR(1),
    raw_death_indicated BOOLEAN NOT NULL DEFAULT FALSE,
    raw_birth_date VARCHAR(255),
    raw_birth_place VARCHAR(255),
    raw_death_date VARCHAR(255),
    raw_death_place VARCHAR(255),
    raw_cause_of_death VARCHAR(255),
    raw_burial_place VARCHAR(255),
    last_imported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_person_gedcom_data_person FOREIGN KEY (person_id)
        REFERENCES people(id) ON DELETE CASCADE
);


CREATE TABLE person_names (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    given_name VARCHAR(255),
    surname VARCHAR(200),
    is_current BOOLEAN NOT NULL,


    CONSTRAINT fk_person_names_person FOREIGN KEY (person_id)
        REFERENCES people(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ux_person_names_current
    ON person_names (person_id)
    WHERE is_current = true;

CREATE INDEX idx_person_names_person_id ON person_names (person_id);



CREATE TABLE families (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    husband_id BIGINT,
    wife_id BIGINT,
    primary_wedding_id BIGINT,
    status_id BIGINT NOT NULL,

    CONSTRAINT at_least_one_parent CHECK (
        husband_id IS NOT NULL OR wife_id IS NOT NULL
    ),
    CONSTRAINT fk_families_husband FOREIGN KEY (husband_id)
        REFERENCES people(id),
    CONSTRAINT fk_families_wife FOREIGN KEY (wife_id)
        REFERENCES people(id),
    CONSTRAINT fk_families_primary_wedding FOREIGN KEY (primary_wedding_id)
        REFERENCES events(id),
    CONSTRAINT fk_families_status FOREIGN KEY (status_id) REFERENCES user_codes(id)
);

CREATE INDEX idx_families_husband_id ON families (husband_id);
CREATE INDEX idx_families_wife_id ON families (wife_id);



CREATE TABLE family_children (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    family_id BIGINT NOT NULL,
    child_id BIGINT NOT NULL,
    relationship_type VARCHAR(50) NOT NULL,

    UNIQUE(family_id, child_id),
    CONSTRAINT fk_family_children_family FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE CASCADE,
    CONSTRAINT fk_family_children_child FOREIGN KEY (child_id) REFERENCES people(id) ON DELETE CASCADE
);

CREATE INDEX idx_family_children_child_id ON family_children (child_id);
CREATE INDEX idx_family_children_family_id ON family_children (family_id);



CREATE TABLE family_gedcom_data (
    family_id BIGINT PRIMARY KEY,
    ged_uid VARCHAR(100),
    ged_ref_id VARCHAR(100) NOT NULL,
    raw_husband_ref_id VARCHAR(100),
    raw_wife_ref_id VARCHAR(100),
    raw_wedding_date VARCHAR(255),
    raw_wedding_place VARCHAR(255),
    raw_status VARCHAR(100),
    last_imported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT at_least_one_parent_gedcom CHECK (
        raw_husband_ref_id IS NOT NULL OR raw_wife_ref_id IS NOT NULL
    ),
    CONSTRAINT fk_family_gedcom_data_family FOREIGN KEY (family_id)
        REFERENCES families(id) ON DELETE CASCADE
);




CREATE TABLE family_child_gedcom_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    raw_relationship_type VARCHAR(100),
    raw_child_ref_id VARCHAR(100) NOT NULL,
    family_gedcom_id BIGINT NOT NULL,

    CONSTRAINT fk_family_child_gedcom_data_family_gedcom
        FOREIGN KEY (family_gedcom_id)
            REFERENCES family_gedcom_data(family_id) ON DELETE CASCADE
);

CREATE INDEX idx_family_child_gedcom_data_family_gedcom_id
    ON family_child_gedcom_data (family_gedcom_id);





CREATE TABLE event_type_participant_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type_id BIGINT NOT NULL,
    participant_role_id BIGINT NOT NULL,

    UNIQUE(event_type_id, participant_role_id),
    CONSTRAINT fk_etpr_gedcom_event_type FOREIGN KEY (event_type_id)
        REFERENCES user_codes(id) ON DELETE CASCADE,
    CONSTRAINT fk_etpr_gedcom_participant_role FOREIGN KEY (participant_role_id)
        REFERENCES user_codes(id) ON DELETE CASCADE
);


CREATE TABLE event_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,

    UNIQUE(event_id, location_id),
    CONSTRAINT fk_event_locations_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT fk_event_locations_location FOREIGN KEY (location_id) REFERENCES locations(id) ON DELETE CASCADE
);

CREATE INDEX idx_event_locations_event_id ON event_locations (event_id);





CREATE TABLE event_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    event_type_participant_role_id BIGINT NOT NULL,

    UNIQUE(event_id, person_id),
    CONSTRAINT fk_ep_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT fk_ep_person FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE,
    CONSTRAINT fk_ep_role FOREIGN KEY (event_type_participant_role_id) REFERENCES event_type_participant_roles(id)
);

CREATE INDEX idx_event_participants_person_id ON event_participants (person_id);





CREATE TABLE graves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cemetery_location_id BIGINT,

    CONSTRAINT fk_graves_cemetery_location FOREIGN KEY (cemetery_location_id)
        REFERENCES locations(id)
);



CREATE TABLE burials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grave_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    burial_event_id BIGINT,
    is_current BOOLEAN DEFAULT TRUE,

    CONSTRAINT fk_burials_grave FOREIGN KEY (grave_id) REFERENCES graves(id),
    CONSTRAINT fk_burials_person FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE,
    CONSTRAINT fk_burials_event FOREIGN KEY (burial_event_id) REFERENCES events(id) ON DELETE SET NULL
);

CREATE INDEX idx_burials_person_id ON burials (person_id);




CREATE TABLE attribute_definitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_code_id BIGINT,
    code VARCHAR(100) NOT NULL,
    data_type VARCHAR(30) NOT NULL,
    is_system BOOLEAN DEFAULT FALSE,

    UNIQUE(user_code_id, code),
    CONSTRAINT fk_attribute_definitions_user_code FOREIGN KEY (user_code_id)
       REFERENCES user_codes(id) ON DELETE CASCADE
);

CREATE TABLE attribute_dictionary_values (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     attribute_definition_id BIGINT NOT NULL,
     code VARCHAR(100) NOT NULL,
     is_system BOOLEAN DEFAULT FALSE,

     UNIQUE(attribute_definition_id, code),
     CONSTRAINT fk_attribute_dictionary_values_attribute_definition FOREIGN KEY (attribute_definition_id)
         REFERENCES attribute_definitions(id) ON DELETE CASCADE
);

CREATE INDEX idx_attribute_dictionary_values_definition_id ON attribute_dictionary_values (attribute_definition_id);




CREATE TABLE event_attribute_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    attribute_dictionary_value_id BIGINT NOT NULL,

    UNIQUE(event_id, attribute_dictionary_value_id),
    CONSTRAINT fk_event_attribute_values_attribute_dictionary_value FOREIGN KEY (attribute_dictionary_value_id)
        REFERENCES attribute_dictionary_values(id) ON DELETE CASCADE,
    CONSTRAINT fk_event_attribute_values_event FOREIGN KEY (event_id)
        REFERENCES events(id) ON DELETE CASCADE
);

CREATE INDEX idx_event_attribute_values_event_id ON event_attribute_values (event_id);




INSERT INTO user_codes (category, code, is_system)
VALUES
    ('EVENT_PARTICIPANT_ROLE', 'PRINCIPAL', TRUE),

    ('EVENT_TYPE', 'BIRTH', TRUE),
    ('EVENT_TYPE', 'WEDDING', TRUE),
    ('EVENT_TYPE', 'DEATH', TRUE),
    ('EVENT_TYPE', 'BURIAL', TRUE),

    ('FAMILY_STATUS', 'MARRIED', TRUE),
    ('FAMILY_STATUS', 'DIVORCED', TRUE),
    ('FAMILY_STATUS', 'SEPARATED', TRUE),
    ('FAMILY_STATUS', 'WIDOWED', TRUE),
    ('FAMILY_STATUS', 'ENGAGED', TRUE),
    ('FAMILY_STATUS', 'PARTNERS', TRUE),
    ('FAMILY_STATUS', 'FRIENDS', TRUE),
    ('FAMILY_STATUS', 'ANNULLED', TRUE),
    ('FAMILY_STATUS', 'UNKNOWN', TRUE),
    ('FAMILY_STATUS', 'OTHER', TRUE),

    ('PERSON_NAME_TYPE', 'BIRTH', TRUE);


INSERT INTO event_type_participant_roles (event_type_id, participant_role_id)
SELECT t.id, r.id
FROM user_codes t, user_codes r
WHERE t.category = 'EVENT_TYPE' AND r.category = 'EVENT_PARTICIPANT_ROLE' AND r.code = 'PRINCIPAL'
  AND t.code IN ('BIRTH', 'DEATH', 'BURIAL', 'WEDDING');

INSERT INTO attribute_definitions (user_code_id, code, data_type, is_system)
VALUES (
       (SELECT id FROM user_codes WHERE category = 'EVENT_TYPE' AND code = 'DEATH'),
       'CAUSE_OF_DEATH',
       'TEXT',
       TRUE
   );