CREATE TABLE people (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cached_given_name VARCHAR(255),
    cached_surname VARCHAR(255),
    sex VARCHAR(20),
    life_state VARCHAR(20)
);

CREATE TABLE person_gedcom_data (
    person_id BIGINT PRIMARY KEY,
    ged_ref_id VARCHAR(100),
    raw_given_name VARCHAR(255),
    raw_surname VARCHAR(255),
    raw_sex VARCHAR(1),
    raw_death_indicated BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_person_gedcom_data_person
        FOREIGN KEY (person_id)
        REFERENCES people (id)
        ON DELETE CASCADE
);