# .github/workflows/ci-pipeline.yml

name: CI Pipeline - Test and Validate PR

on:
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  validate-backend:
    name: Validate Backend (in Docker)
    runs-on: ubuntu-latest
    
    container:
      image: gradle:8.8.0-jdk21-alpine
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - uses: actions/checkout@v4
  
      - name: Make gradlew executable
        run: chmod +x ./backend/gradlew
        
      - name: Run tests and build application
        working-directory: ./backend
        run: ./gradlew build

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-reports
          path: backend/build/reports/tests/test/


  validate-frontend:
    name: Validate Frontend (in Docker)
    runs-on: ubuntu-latest
    
    container:
      image: node:20-alpine

    steps:
      - uses: actions/checkout@v4
            
      - name: Install dependencies, lint and build
        working-directory: ./frontend
        run: |
          npm ci
          npm run lint
          npm run build

  validate-compose-files:
    name: Validate Docker Compose Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker-compose.yml config
      - run: docker compose -f docker-compose.staging.yml config
      - run: docker compose -f docker-compose.prod.yml config